import Vue from 'vue'

import {
  ActionSheet,
  AddressEdit,
  AddressList,
  Area,
  Badge,
  Button,
  Card,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  CollapseItem,
  ContactCard,
  ContactEdit,
  ContactList,
  CouponCell,
  CouponList,
  DatetimePicker,
  Divider,
  Dialog,
  Field,
  GoodsAction,
  Grid, GridItem,
  Icon,
  ImagePreview,
  Info,
  Lazyload,
  List,
  Loading,
  Locale,
  NavBar,
  NoticeBar,
  Notify,
  NumberKeyboard,
  Overlay,
  Pagination,
  Panel,
  PasswordInput,
  Picker,
  Popup,
  Progress,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  Search,
  Sku,
  Slider,
  Step,
  Stepper,
  Steps,
  SubmitBar,
  Swipe,
  SwipeCell,
  SwipeItem,
  Switch,
  SwitchCell,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader,
  Empty,
  Image,
  Form
} from 'vant'

Vue.use(ActionSheet)
  .use(Image)
  .use(Form)
  .use(AddressEdit)
  .use(AddressList)
  .use(Area)
  .use(Badge)
  .use(Button)
  .use(Card)
  .use(Cell)
  .use(CellGroup)
  .use(Checkbox)
  .use(CheckboxGroup)
  .use(Circle)
  .use(Col)
  .use(Collapse)
  .use(CollapseItem)
  .use(ContactCard)
  .use(ContactEdit)
  .use(ContactList)
  .use(CouponCell)
  .use(CouponList)
  .use(DatetimePicker)
  .use(Dialog)
  .use(Divider)
  .use(Field)
  .use(GoodsAction)
  .use(Grid)
  .use(GridItem)
  .use(Icon)
  .use(ImagePreview)
  .use(Info)
  .use(Lazyload)
  .use(List)
  .use(Loading)
  .use(Locale)
  .use(NavBar)
  .use(NoticeBar)
  .use(Notify)
  .use(NumberKeyboard)
  .use(Overlay)
  .use(Pagination)
  .use(Panel)
  .use(PasswordInput)
  .use(Picker)
  .use(Popup)
  .use(Progress)
  .use(PullRefresh)
  .use(Radio)
  .use(RadioGroup)
  .use(Rate)
  .use(Row)
  .use(Search)
  .use(Sku)
  .use(Slider)
  .use(Step)
  .use(Stepper)
  .use(Steps)
  .use(SubmitBar)
  .use(Swipe)
  .use(SwipeCell)
  .use(SwipeItem)
  .use(Switch)
  .use(SwitchCell)
  .use(Tab)
  .use(Tabbar)
  .use(TabbarItem)
  .use(Tabs)
  .use(Tag)
  .use(Toast)
  .use(TreeSelect)
  .use(Uploader)
  .use(Empty)
